// UI actions
export const TOGGLE_SELECTION_CRITERIA = 'TOGGLE_SELECTION_CRITERIA'
export const TOGGLE_SELECTION_RESULTS = 'TOGGLE_SELECTION_RESULTS'
export const OPEN_PANELS = 'OPEN_PANELS'
export const TOGGLE_ANALYTICS_EVENTS_TABLE = 'TOGGLE_ANALYTICS_EVENTS_TABLE'
export const TOGGLE_ANALYTICS_PATTERNS_TABLE = 'TOGGLE_ANALYTICS_PATTERNS_TABLE'
export const MINIMIZE_ANALYTICS_PATTERNS_TABLE = 'MINIMIZE_ANALYTICS_PATTERNS_TABLE'

// Selection Results actions
export const SET_SELECTION_RESULTS_FILTER = 'SET_SELECTION_RESULTS_FILTER'
export const SELECT_SELECTION_RESULT = 'SELECT_SELECTION_RESULT'
export const DESELECT_SELECTION_RESULT = 'DESELECT_SELECTION_RESULT'
export const ADD_SELECTED_AGGREGATION = 'ADD_SELECTED_AGGREGATION'
export const SET_SELECTED_GRANULARITY = 'SET_SELECTED_GRANULARITY'
export const SET_AGGREGATION_CONSOLIDATIONS = 'SET_AGGREGATION_CONSOLIDATIONS'
export const DELETE_AGGREGATION_CONSOLIDATIONS = 'DELETE_AGGREGATION_CONSOLIDATIONS'
export const DISPLAY_AGGREGATION_FROM_DASHBOARD = 'DISPLAY_AGGREGATION_FROM_DASHBOARD'
export const SET_CHART_EVENTS = 'SET_CHART_EVENTS'
export const SET_PATTERNS = 'SET_PATTERNS'
export const TOGGLE_PATTERN_DISPLAY = 'TOGGLE_PATTERN_DISPLAY'
export const SET_PATTERN_INFO = 'SET_PATTERN_INFO'

// Selection Criteria actions
export const SHOW_FLYOUT = 'SHOW_FLYOUT'
export const HIDE_FLYOUT = 'HIDE_FLYOUT'
export const SELECT_LABEL_TYPE = 'SELECT_LABEL_TYPE'
export const TOGGLE_LABEL = 'TOGGLE_LABEL'
export const SHOW_SHORTCUT = 'SHOW_SHORTCUT'
export const HIDE_SHORTCUT = 'HIDE_SHORTCUT'
export const SEARCH_TREE_LABELS = 'SEARCH_TREE_LABELS'
export const LOAD_LABEL_TREES = 'LOAD_LABEL_TREES'
export const UPDATE_SEARCH_CRITERIA_RESULTS = 'UPDATE_SEARCH_CRITERIA_RESULTS'
export const CLEAR_SEARCH_CRITERIA_RESULTS = 'CLEAR_SEARCH_CRITERIA_RESULTS'
export const SEARCH_LABEL_TYPE_LABELS = 'SEARCH_LABEL_TYPE_LABELS'
export const LOAD_INITIAL_TREES = 'LOAD_INITIAL_TREES'

// Navbar actions
export const SHOW_DATETIME_RANGE_SELECT = 'SHOW_DATETIME_RANGE_SELECT'
export const HIDE_DATETIME_RANGE_SELECT = 'HIDE_DATETIME_RANGE_SELECT'
export const SET_DATE_RANGE = 'SET_DATE_RANGE'
export const SET_QUICK_RANGE = 'SET_QUICK_RANGE'

// Dashboard actions
export const SHOW_LOCATION_FLYOUT = 'SHOW_LOCATION_FLYOUT'
export const HIDE_LOCATION_FLYOUT = 'HIDE_LOCATION_FLYOUT'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const CHANGE_MINI_CARD = 'CHANGE_MINI_CARD'
export const INIT_KPI_LOCATION = 'INIT_KPI_LOCATION'
export const INIT_KPI_CARDS = 'INIT_KPI_CARDS'

export const SET_MINICARD_CONSOLIDATIONS = 'SET_MINICARD_CONSOLIDATIONS'
export const UPDATE_MINICARD_MAX = 'UPDATE_MINICARD_MAX'
export const UPDATE_MINICARD_MIN = 'UPDATE_MINICARD_MIN'
export const UPDATE_MINICARD_TARGET = 'UPDATE_MINICARD_TARGET'
export const SET_RELIABILITY_MIN = 'SET_RELIABILITY_MIN'
export const SET_RELIABILITY_VALUE = 'SET_RELIABILITY_VALUE'

// Events actions
export const SHOW_CREATE_EVENT_FORM = 'SHOW_CREATE_EVENT_FORM'
export const HIDE_CREATE_EVENT_FORM = 'HIDE_CREATE_EVENT_FORM'

export const SHOW_CREATE_EVENT_LOCATION_FLYOUT = 'SHOW_CREATE_EVENT_LOCATION_FLYOUT'
export const HIDE_CREATE_EVENT_LOCATION_FLYOUT = 'HIDE_CREATE_EVENT_LOCATION_FLYOUT'
export const SELECT_CREATE_EVENT_LOCATION_LABEL_TYPE = 'SELECT_CREATE_EVENT_LOCATION_LABEL_TYPE'
export const SELECT_CREATE_EVENT_LOCATION_LABEL = 'SELECT_CREATE_EVENT_LOCATION_LABEL'
export const SEARCH_CREATE_EVENT_LOCATION_LABEL_TYPE_LABELS = 'SEARCH_CREATE_EVENT_LOCATION_LABEL_TYPE_LABELS'

export const SHOW_EDIT_EVENT_TYPE_FLYOUT = 'SHOW_EDIT_EVENT_TYPE_FLYOUT'
export const HIDE_EDIT_EVENT_TYPE_FLYOUT = 'HIDE_EDIT_EVENT_TYPE_FLYOUT'
export const SELECT_EDIT_EVENT_TYPE_LABEL_TYPE = 'SELECT_EDIT_EVENT_TYPE_LABEL_TYPE'
export const SELECT_EDIT_EVENT_TYPE_LABEL = 'SELECT_EDIT_EVENT_TYPE_LABEL'
export const SEARCH_EDIT_EVENT_TYPE_LABEL_TYPE_LABELS = 'SEARCH_EDIT_EVENT_TYPE_LABEL_TYPE_LABELS'

export const SELECT_EDIT_EVENT_TYPE = 'SELECT_EDIT_EVENT_TYPE'

export const EDIT_EVENT_UPDATE_EQUIPMENT = 'EDIT_EVENT_UPDATE_EQUIPMENT'

// Event Edit
export const SHOW_EVENT_EDIT_DATE_SELECT = 'SHOW_EVENT_EDIT_DATE_SELECT'
export const HIDE_EVENT_EDIT_DATE_SELECT = 'HIDE_EVENT_EDIT_DATE_SELECT'
export const SET_EVENT_EDIT_DATE = 'SET_EVENT_EDIT_DATE'

// Event Search
export const SHOW_SEARCH_EVENTS_FORM = 'SHOW_SEARCH_EVENTS_FORM'
export const HIDE_SEARCH_EVENTS_FORM = 'HIDE_SEARCH_EVENTS_FORM'
export const SHOW_EVENTS_SEARCH_DATE_SELECT = 'SHOW_EVENTS_SEARCH_DATE_SELECT'
export const HIDE_EVENTS_SEARCH_DATE_SELECT = 'HIDE_EVENTS_SEARCH_DATE_SELECT'
export const SET_EVENTS_SEARCH_DATE = 'SET_EVENTS_SEARCH_DATE'
export const SEARCH_EVENTS = 'SEARCH_EVENTS'

// User
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

// Patterns actions
export const SHOW_ADD_PATTERNS_FORM = 'SHOW_ADD_PATTERNS_FORM'
export const HIDE_ADD_PATTERNS_FORM = 'HIDE_ADD_PATTERNS_FORM'
export const SHOW_SEARCH_PATTERNS_FORM = 'SHOW_SEARCH_PATTERNS_FORM'
export const HIDE_SEARCH_PATTERNS_FORM = 'HIDE_SEARCH_PATTERNS_FORM'
export const ADD_PATTERN_SUCCESSFUL = 'ADD_PATTERN_SUCCESSFUL'
export const ADD_PATTERN_FAILED = 'ADD_PATTERN_FAILED'
export const ASSOCIATE_PATTERN_SUCCESSFUL = 'ASSOCIATE_PATTERN_SUCCESSFUL'
export const ASSOCIATE_PATTERN_FAILED = 'ASSOCIATE_PATTERN_FAILED'
export const HIDE_POPUP_MESSAGE = 'HIDE_POPUP_MESSAGE'
